### ISSUE TITLE
🔬 Study Creation Automation

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#232]
As internal administrators, it would be convenient to have a single entrypoint to create a study in which all tasks associated with setting up a new study would be performed automatically. This would be helpful as any tedious manual work that needs to be done in setting up a study may be automated and we can be ensured that each study has been configured in a consistent manner.

- [x] #14 -> #219 - Create studies in study-creator and sync to dataservice
- [x] #222 -> #225 - Update studies in study-creator and dataservice
- [x] #220 -> #244 - Add description to study model
- [x] #216 -> #227 - Create project model for Cavatica projects
- [x] #241 -> #242 - Add workflow_type field to project model
- [x] #217 -> #229 - Create base projects in Cavatica when creating studies
- [x] #246 -> #249 - Anticipated samples field
- [x] #247 -> #249 - Awardee organization field
- [x] #231 -> #273 - Add bix users to new Cavatica projects
- [x] #233 -> #287 - Attach volumes for new Cavatica projects
- [x] #263 -> #264 - Allow different workflows to be configured per-study
- [x] #275 -> #276 - Create projects for new workflows
