### ISSUE TITLE
DataReview Model

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#548]
## Overview
We are adding a new feature to the Data Tracker which allows stakeholders to use Data Tracker to facilitate a Data Review - a process in which stakeholders validate, refine, and ultimately ingest their data into the Kids First Data Service.

A new model should be added to the study creator API to support this feature. This will involve designing the life cycle of the Data Review and the relational model which captures the life cycle and characteristics of the Data Review concept

## Tasks

-   [x] Document describing/illustrating Data Review life cycle
-   [x] Document illustrating Data Review relational model
-   [ ] Implement + test DataReview model in Study Creator

## Design Considerations

-   A Data Review is a process with multiple stages or states (e.g. started, validating, validated, in-review, approved, etc.)

-   A Data Review is related to a set of documents or file versions

-   A Study may have multiple Data Reviews for a unique set of documents before those documents are ingested into production.

1.  What uniquely identifies a Data Review?

    - ❌ A unique set of documents OR a unique set of file versions?
    - ✅ A review will be uniquely identified with an autogenerated unique id. The docs/files will not uniquely identify the review 
since we want the ability to add/remove documents to the same review.

2.  What events/actions cause a Data Review to begin and end?

    - ✅ Begin: After creation of DataReview instance when state goes to started
    - ✅ End : when DataReview state changes to closed or completed

3.  Can a study have multiple "open" Data Reviews at any given point in time?

    - ✅ Yes. Examples: study has multiple batches of documents that we want to review independently

4.  What happens when a document or file version is deleted (or attempted)
    and it is already part of an open DataReview?

        - ❌ Option 1: Not allowed until review is in a closed/completed state
        - ❌ Option 2: Review is automatically closed upon deletion
        - ✅ Option 3: Review stays open, but the related set of documents/files changes

5.  How does a DataReview relate to a "validation run"?

    - A DataReview may have multiple validation runs

6.  What is a "validation run"?

    - ❌ An IngestRun with specific input parameters setup for validation only
    - ✅ A new concept called ValidationRun with a state machine similar to IngestRun. A validation run produces a validation report

7.  What happens when a new file version is added to a document that is part
    of an open Data Review?
- ✅ The user is notified via an event in the timeline
