### ISSUE TITLE
Add intermediate states to ingest processes

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#636]
When a user clicks the button to cancel a run, there is a noticeable delay between the request to cancel the run and the completion of the cancellation since canceling requires queuing a background task which doesn't start right away. There are similar issues with starting a validation run run. 

### TODO:

We should add a `cancelling` state to the `IngestProcess` model (which is inherited by validation run model). The `IngestProcess` state transition methods will need to change a bit:

- [ ] Replace the `IngestProcess.cancel` method with `IngestProcess.start_cancel` and `IngestProcess.complete_cancel`
- [ ] Update the cancel mutations for both ingest run and validation run to call the start cancel method before the cancel task is queued
- [ ] Update the cancel tasks for both ingest run and validation run to call the complete cancel method instead of the old cancel method

We should add an `initializing` state to `IngestProcess` model (which is inherited by validation run model). The `IngestProcess` state transition methods will need to change a bit:

- [ ] Replace the `IngestProcess.start` method with `IngestProcess.initialize` and `IngestProcess.start`
- [ ] Update the start mutations for both ingest run and validation run to call the initialize method before the start task is queued
- [ ] Update the start tasks for both ingest run and validation run to call the initialize method instead of the old start method
