### ISSUE TITLE
Capture reason for failed ingest processes

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-api-study-creator#637]
When a validation run fails an exception is raised with a useful error message, however this message is not stored or sent back to the frontend since the exception happens in an async worker. This results in the user not knowing why a run failed. 

We should add an `error_msg` field to the `IngestProcess` model (this gets inherited by `IngestRun` and `ValidationRun`) that will get populated in the ingest process task.

### Todo:

- [x] Add `IngestProcess.error_msg`
- [x] Update the `run_ingest` task and `run_validation` task to populate this field in the exception handler before the fail method is called on the run
- [x] Update tests to reflect this new field

**Comment by gsantia** [comment]
For the `run_validation` function, as it it's formatted now, should it just be a single error message? This is what I mean:
```python
try:
        results = validate_file_versions(vr)
        report_markdown = build_report(results)
        vrs = persist_results(results, report_markdown, vr)
    except Exception:
        vr.success = False
        vr.error_msg = (
            "An error occurred during the validation process. Check the logs "
            "for more details."
        )
        vr.fail()
```

If an exception occurs here we won't know which of the 3 lines caused it. Should it be more specific? I.E. should there be a separate try/except block for each of the 3 lines so we can have 3 different error messages?
        vr.save()
        raise

**Comment by znatty22** [comment]
I think this error message should capture the specific error. So I would change what I requested in the original issue description. This field should be populated with an error message anytime an exception is about to be raised in the run validation task (e.g. None of the versions had extract configs, a version was missing the root file, etc). I think you would basically just take the same message being supplied to the exception constructor and use that for the error message.
